// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authorization.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const isChatMember = `-- name: IsChatMember :one
SELECT EXISTS(
    SELECT 1
    FROM chat_members
    WHERE chat_id = $1 AND user_id = $2
) AS is_member
`

type IsChatMemberParams struct {
	ChatID uuid.UUID `json:"chat_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) IsChatMember(ctx context.Context, arg IsChatMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isChatMember, arg.ChatID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}
