// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Chat struct {
	ID        uuid.UUID      `json:"id"`
	Name      sql.NullString `json:"name"`
	IsGroup   bool           `json:"is_group"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	CreatedBy uuid.UUID      `json:"created_by"`
}

type ChatMember struct {
	ID        uuid.UUID    `json:"id"`
	ChatID    uuid.UUID    `json:"chat_id"`
	UserID    uuid.UUID    `json:"user_id"`
	JoinedAt  time.Time    `json:"joined_at"`
	ClearedAt sql.NullTime `json:"cleared_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Image struct {
	ID        uuid.UUID `json:"id"`
	MessageID uuid.UUID `json:"message_id"`
	Url       string    `json:"url"`
	CreatedAt time.Time `json:"created_at"`
}

type Message struct {
	ID               uuid.UUID      `json:"id"`
	ChatID           uuid.UUID      `json:"chat_id"`
	SenderID         uuid.UUID      `json:"sender_id"`
	Content          sql.NullString `json:"content"`
	IsDeleted        bool           `json:"is_deleted"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	IsEdited         bool           `json:"is_edited"`
	ReplyToMessageID uuid.NullUUID  `json:"reply_to_message_id"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
